### ISSUE TITLE
[Feature] VB.Net Compatibility

### ISSUE THREAD

**Issue by beppe9000** [bonyjoe/EnvVariableInject#1]

**Comment by donocode** [comment]
VB.Net should not need any specific support for compatibility. However you will need to create the attribute in VB.Net instead of using the generated C# one.

The following should work

``` vb
<AttributeUsage(AttributeTargets.Field)> 
Class BuildTimeEnvironmentVariableAttribute Inherits System.Attribute
    Private _environmentVariable As String

    Public Sub New(ByVal environmentVariable As String)
        _environmentVariable = environmentVariable
    End Sub
End Class
```

The requirements are that the name of the attribute is `BuildTimeEnvironmentVariableAttribute` and the first constructor argument is a string, this will allow EnvVariableInject to find the fields.

I will look into including an auto generated .vb version of the attribute as well as the .cs

**Comment by beppe9000** [comment]
Yes, I extactly meant this. Right now the nuget adds the cs even to vb projects.

**Comment by donocode** [comment]
I've added the VB.NET attribute to be copied in at install time. Nuget copies files regardless of language so I've modified the install script to delete either the vb or cs file depending on the language of the project the package is being installed into.

**Comment by beppe9000** [comment]
Wow, that's an awkward limitation...
